# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('trust-routing', ['core', 'network'])
    module.source = [
        'model/trust-manager.cc',
        'model/trust-entry.cc',
        'model/trust-table.cc',
        'helper/trust-manager-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('trust-routing')
    module_test.source = [
        'test/trust-routing-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'trust-routing'
    headers.source = [
        'model/trust-manager.h',
        'model/trust-entry.h',
        'model/trust-table.h',
        'helper/trust-manager-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

